# Дана целочисленная квадратная матрица. Определить:
1. Сумму элементов в тех столбцах, которые не содержат отрицательных элементов;
2. Минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали
матрицы.

Инициализирую матрицу и импортирую NumPy

In [2]:
import numpy as np 

In [5]:
n = int(input("Enter the size of the matrix: "))

Enter the size of the matrix: 5


In [14]:
matrix = np.random.randint(-20, 100, (n, n))
print(matrix)

[[ 13  59  83  69  -4]
 [ 32  33   4  20  33]
 [ 49  34  25 -17  96]
 [ -5   7  90  13  76]
 [ 53  82  49  94  63]]


# 1.  Сумма элементов в тех столбцах, которые не содержат отрицательных элементов

Вывожу массив boolean по столбац, в которых минимальный элемент больше нуля:

In [20]:
print(matrix.min(axis=0) > 0)

[False  True  True False False]


Здесь я уже попытался вывести только столбцы матрицы, которые не содержали отрицательных элементов:

In [25]:
print(matrix[:, matrix.min(axis=0) > 0])

[[59 83]
 [33  4]
 [34 25]
 [ 7 90]
 [82 49]]


Узнав как получить доступ к нужным мне столбцам, посчитал их сумму:

In [26]:
summa = np.sum(matrix[:, matrix.min(axis=0) > 0])
print(summa)

466


# 2. Минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали матрицы

In [2]:
import numpy as np 

In [3]:
n = int(input("Enter the size of the matrix: "))

Enter the size of the matrix: 5


После ввода размерности матрицы задаю матрицу со случайными числами. Затем применяю к матрице модуль, чтобы посчитать сумму модулей элементов.

In [15]:
matrix = np.random.randint(-20, 300, (n, n))
matrix = np.absolute(matrix)
print(matrix)

[[101  11 150 151 201]
 [ 62 112 256  99   2]
 [101 103 197 173 248]
 [129  73  56  19 297]
 [ 35 293 150 280 234]]


Минимум сумм находится функцией min, применённой к списку, элементами которого являются суммы диагоналей, возвращаемые функцией trace() со смещением по диагоналей, параллельным побочной диагонали. Они высчитываются благодаря перевороту матрицы функцией fliplr().

In [17]:
min_sum = min([np.fliplr(matrix).trace(offset=i) for i in range(-(n-1), n)])
print(min_sum)

73
